nameOverride: "frontend"

global:
  imageRegistry: "helmdeploymentappdevacr.azurecr.io"

image:
  repository: <repo_name>
  tag: <image_tag>

service:
  port: 80

ingress:
  enabled: true
  domain: "snaplink.com"

healthPath: "/"